version: '3.8'

services:
  backend:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: "postgresql://usuario:password@ep-neon-host.compute-1.amazonaws.com:5432/tickets"
    depends_on:
      - migrations

  migrations:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "npm install && npx prisma migrate deploy"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
